#include "strings.h"
#include <stdint.h>

char* global_string[NUM_STRINGS]= {
     (char*)"Are you sure you want to exit?",
     (char*)"Are you sure?",
     (char*)"Enter name for this file:",
     (char*)"Baud",
     (char*)"Select baud",
     (char*)"BBS",
     (char*)"Enter URL and port",
     (char*)"Hang up?",
     (char*)"Yes",
     (char*)"No",
     (char*)"OK",
     (char*)"Cancel",
     (char*)"MAIN MENU",
     (char*)"b Set Baud",
     (char*)"f Fone Home",
     (char*)"d Dial a BBS",
     (char*)"a About",
     (char*)"q Quit",
     (char*)"Error: Could not initialize serial comms",
     (char*)"Error: Serial overflow",
     (char*)"Unknown ANSI sequence: %s",
     (char*)"Generic Error!",
     (char*)"Fatal error %u",
     (char*)"We don't need no stinkin' error messages",
     (char*)"A disk error occurred",
     (char*)"Out of memory error",
     (char*)"Scanning for drives...",
     (char*)"%u drives found",
     (char*)"Hit any key",
     (char*)"Available memory: %zu bytes",
     (char*)"Serial buffer saved to disk",
     (char*)"300 baud was good enough for WOPR, it's good enough for you.",
     (char*)"1200 baud: Volksmodem unlocked!",
     (char*)"2400 baud and flying!",
     (char*)"Trueish fact: Nobody ever advertised a 3600 baud modem.",
     (char*)"4800 baud is 16 times faster than a VIC modem.",
     (char*)"9600 baud is to 8-bits what 88 mph is to a Delorean: attainable but only just.",
     (char*)"19200 baud... Hope that's a 68000 in your pocket.",
     (char*)"38400 baud. I think you overestimate your skilz.",
     (char*)"57600 baud. US Robotics for the win!",
     (char*)"115200 baud. I think you overestimate my skilz.",
     (char*)"   300",
     (char*)"   600",
     (char*)"  1200",
     (char*)"  2400",
     (char*)"  3600",
     (char*)"  4800",
     (char*)"  9600",
     (char*)" 19200",
     (char*)" 38400",
     (char*)" 57600",
     (char*)"115200",
     (char*)"ANSI charset with Foenix-style font selected.",
     (char*)"ANSI charset with IBM-style font selected.",
     (char*)"Japanese charset (JIS X 0201) with Foenix-style font selected.",
     (char*)"Foenix charset selected.",
     (char*)"https://github.com/WartyMN/f256-fterm/",
     (char*)"F256 f/term %c2024 Micah Bly. Version %u.%u.%u.",
     (char*)"F256JR",
     (char*)"F256K",
     (char*)"F256K2",
     (char*)"<unknown hardware>",
};




